### ISSUE TITLE
All 360 songs now insta-fail me, even non-auto generated ones

### ISSUE THREAD

**Issue by mchety** [CodeStix/Beat-360fyer-Plugin#1]
Since I've installed this mod, all of my custom 360+90 degree songs insta-fail me if I miss one note, or get a bad hit. I've made sure insta-fail is off, and I've even un-installed the mod, and the issue persists. The auto-generated maps load alright, and I can play them on no-fail, and for some reason, OST 360+90 maps don't insta-fail me. Any help would be greatly appreciated. (Let me know if I should give more info)

**Comment by CodeStix** [comment]
Hey, I tried reproducing your issue, but couldn't get the behaviour you were experiencing.  (I tried everything)

Did you use the newest version of the plugin, if not, does installing the newest version help?
Do you have the `CustomJSONData` plugin installed, if not, does this help?
Did you try to repatch? (drag & drop `Beat Saber.exe` onto `IPA.exe`)
Did you try to remove all other plugins temporarily?

If these do not help, can you send me a zip containing all your installed plugins, so I can try to take a look which plugins are messing this up?

I hope we can work this out!

**Comment by mchety** [comment]
Thanks for trying to replicate the issue, I'm gonna go do some more trouble shooting, and I'll let you know if I can fix it.

**Comment by mchety** [comment]
Ok, so after doing some troubleshooting, I'm thinking this issue may be unrelated to the mod since after removing the mod, it keeps happening. When I removed all of my mods though, I wasn't insta-failing. I also saw that someone on the BSMG discord had the same issue a couple of weeks ago. So my guess is some other mod is just messing with custom 360 maps. Thanks for your help though!

**Comment by CodeStix** [comment]
No problem!
