### ISSUE TITLE
Not single saber?

### ISSUE THREAD

**Issue by Kaltern** [CodeStix/Beat-360fyer-Plugin#3]
Is there any reason this won't work with single saber maps? You might want to change the description of the mod otherwise... :)

**Comment by CodeStix** [comment]
Hmm, I should add an option to make that possible. I will close this issue once the feature has been added.

**Comment by Kaltern** [comment]
That would be very much appreciated! I can only play one-handed maps, and to have this as an extra challenge would be great :D

**Comment by CodeStix** [comment]
Hey, the feature is now available. Here is how to use it:

1. Download the new version [here](https://github.com/CodeStix/Beat-360fyer-Plugin/releases/latest), also make sure you've got the **CustomJSONData** plugin installed too.
2. Place the plugin in your `Plugins` folder
3. Open and then close the game. (will update the plugin)
4. Open the `Beat-360fyer-Plugin.json` file with notepad or any text editor. (The file is located in your Beat Saber folder under UserData)

**Now that you have the file open, you have 2 options:**
1. Generate only 360 modes for levels that have the **OneSaber** gamemode by changing the `"BasedOn"` property to `"OneSaber"` like this:

    ```json
   {
     "ShowGenerated360": true,
     "ShowGenerated90": true,
     "EnableWallGenerator": true,
     "LimitRotations360": 28,
     "LimitRotations90": 2,
     "BasedOn": "OneSaber",
     "OnlyOneSaber": false
   }
    ```

2. **OR** use the experimental 360 OneSaber generator that allows you to play any Standard level in 360 degree OneSaber mode by changing the `"OnlyOneSaber"` property to `true` (a bit janky but you should try it :smile:):

    ```json
   {
     "ShowGenerated360": true,
     "ShowGenerated90": true,
     "EnableWallGenerator": true,
     "LimitRotations360": 28,
     "LimitRotations90": 2,
     "BasedOn": "Standard",
     "OnlyOneSaber": true
   }
    ```

If you need any more help, you can leave a comment below.

**Comment by Kaltern** [comment]
I’ll give it a go and let you know how it goes – Thanks for doing it, I suspect I’m not the only one who will appreciate!

**Comment by Kaltern** [comment]
So um... WOW!

That has got to be the craziest, most fun thing I've done on BS for absolutely ages.

One Saber mode in 90º mode is utterly superb. I get the feeling the maps are identical each time, so they're valid scoresaber maps?

Absolute legend, thank you for making this happen! 

Only one bug I have found - one miss = immediate fail.. that needs to be addressed! Please? 🤣

**Comment by CodeStix** [comment]
No problem! :smile: 

I have seen this insta fail problem before, please look at [this issue](https://github.com/CodeStix/Beat-360fyer-Plugin/issues/1#issue-866441976) for more information. If those instructions do not resolve your problem, please reopen the  issue.
